CourseManagement/Areas/Admin/Models/LoginViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CourseManagement.Areas.Admin.Models
{
    public class LoginViewModel
    {
        [Key]
        [MaxLength(100)]
        [Required(ErrorMessage = ("Vui lòng nhập Username"))]
        [Display(Name = "Username")]
        public string UserName { get; set; }

        [Display(Name = "Mật khẩu")]
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu")]
        [MinLength(5, ErrorMessage = "Bạn cần đặt mật khẩu tối thiểu 5 ký tự")]
        public string Password { get; set; }
    }
}

CourseManagement/Areas/Admin/Controllers/AdminAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CourseManagement.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using AspNetCoreHero.ToastNotification.Notyf;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using PagedList.Core;
using System.Security.Claims;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using System.Linq.Expressions;
using Newtonsoft.Json.Linq;
using static System.Net.Mime.MediaTypeNames;
using Microsoft.AspNetCore.Rewrite;
using System.Security.Principal;
using CourseManagement.Extension;
using CourseManagement.Areas.Admin.Models;


namespace CourseManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminAccountsController : Controller
    {
        private readonly CourseDatabaseContext _context;
        public INotyfService _notyf;

        public AdminAccountsController(CourseDatabaseContext context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }

       
        public IActionResult Index(int IdRole = 0, int page = 1)
        {
            var pageNumber = page;
            var pageSize = 10;

            List<Account> lsAccounts = new List<Account>();

            if (IdRole != 0)
            {
                lsAccounts = _context.Accounts
                .AsNoTracking()
                .Where(x => x.IdRole == IdRole)
                .Include(x => x.IdRoleNavigation)
                .OrderBy(x => x.IdAccount).ToList();
            }
            else
            {
                lsAccounts = _context.Accounts
                .AsNoTracking()
                .Include(x => x.IdRoleNavigation)
                .OrderBy(x => x.IdAccount).ToList();
            }

            PagedList<Account> models = new PagedList<Account>(lsAccounts.AsQueryable(), pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            ViewBag.PageLength = (int)Math.Ceiling((Double)lsAccounts.Count / (Double)pageSize);
            ViewBag.CurrentIdRole = IdRole;
            ViewData["IdRole"] = new SelectList(_context.Roles, "IdRole", "Name");
            return View(models);
        }
       
        public IActionResult Create()
        {
            ViewData["IdRole"] = new SelectList(_context.Roles, "IdRole", "Name");
            _notyf.Information("Đang thêm mới");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdAccount,Username,Password,Fullname,Phone,Active,IdRole")] Account account)
        {

            if (ModelState.IsValid)
            {
                if (AccountExists(account.Username))
                {
                    _notyf.Error("Tài khoản đã được sử dụng");
                    ViewData["IdRole"] = new SelectList(_context.Roles, "IdRole", "Name");
                    return View();
                }
                if (account.IdRole == 0 || account.IdRole == null || account.Fullname == null || account.Phone == null)
                {
                    _notyf.Error("Chưa nhập đầy đủ thông tin");
                    ViewData["IdRole"] = new SelectList(_context.Roles, "IdRole", "Name");
                    return View();
                }

                account.Password = account.Password.Trim().ToMD5();
          
                _context.Add(account);
                await _context.SaveChangesAsync();
                _notyf.Success("Tạo mới thành công");
                return RedirectToAction(nameof(Index));
            }

            _notyf.Error("Chưa nhập đầy đủ thông tin");
            ViewData["IdRole"] = new SelectList(_context.Roles, "IdRole", "Name");
            return View(account);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Accounts == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts.FindAsync(id);
            if (account == null)
            {
                return NotFound();
            }
            ViewData["IdRole"] = new SelectList(_context.Roles, "IdRole", "Name", account.IdRole);
            _notyf.Warning("Đang chỉnh sửa");
            return View(account);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdAccount,Username,Password,Fullname,Phone,Active,IdRole")] Account account)
        {
            if (id != account.IdAccount)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (account.IdRole == 0 || account.IdRole == null || account.Fullname == null || account.Phone == null)
                    {
                        _notyf.Error("Chưa nhập đầy đủ thông tin");
                        ViewData["IdRole"] = new SelectList(_context.Roles, "IdRole", "Name");
                        return View();
                    }

                    _context.Update(account);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    _notyf.Error("Vui lòng thử lại");
                    ViewData["IdRole"] = new SelectList(_context.Roles, "IdRole", "Name");
                    return View();
                }
                _notyf.Success("Chỉnh sửa thành công");
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdRole"] = new SelectList(_context.Roles, "IdRole", "Name", account.IdRole);
            return View(account);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Accounts == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts
                .Include(a => a.IdRoleNavigation)
                .FirstOrDefaultAsync(m => m.IdAccount == id);
            if (account == null)
            {
                return NotFound();
            }
            _notyf.Error("Xác nhận xóa");
            return View(account);
        }
    
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Accounts == null)
            {
                return Problem("Entity set 'CourseDatabaseContext.Accounts'  is null.");
            }
            var account = await _context.Accounts.FindAsync(id);
            if (account != null)
            {
                _context.Accounts.Remove(account);
            }

            await _context.SaveChangesAsync();
            _notyf.Success("Xóa thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool AccountExists(string Username)
        {
            List<Account> lsAccounts = new List<Account>();

            lsAccounts = _context.Accounts
            .AsNoTracking()
                .Where(x => x.Username.Trim() == Username.Trim())
                .OrderBy(x => x.IdAccount).ToList();
            if (lsAccounts.Count > 0) return true;
            return false;
        }

        public async Task<IActionResult> ChangePassword(int? id)
        {
            if (id == null || _context.Accounts == null)
            {
                return NotFound();
            }

            var account = await _context.Accounts.FindAsync(id);
            if (account == null)
            {
                return NotFound();
            }
            _notyf.Information("Đang đổi mật khẩu");
            ViewData["IdRole"] = new SelectList(_context.Roles, "IdRole", "Name");
            return View(account);
        }

        [HttpPost, ActionName("ChangePassword")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(int id, [Bind("IdAccount,Username,Password,Fullname,Phone,Active,IdRole")] Account account)
        {
            if (id != account.IdAccount)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (account.Password == null)
                    {
                        _notyf.Error("Chưa nhập mật khẩu");
                        ViewData["IdRole"] = new SelectList(_context.Roles, "IdRole", "Name");
                        return View();
                    }

                    account.Password = account.Password.Trim().ToMD5();

                    _context.Update(account);
                    _notyf.Success("Đổi mật khẩu thành công");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    _notyf.Error("Vui lòng thử lại");
                    return View();
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdRole"] = new SelectList(_context.Roles, "IdRole", "Name");
            return View(account);
        }


        [AllowAnonymous]
        [Route("/dang-nhap.html", Name = "Login")]
        public IActionResult Login()
        {
            var khID = HttpContext.Session.GetString("IdAccount");
            if (khID != null) return RedirectToAction("Index", "AdminDashboard", new { Area = "Admin" });
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [Route("/dang-nhap.html", Name = "Login")]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            try
            {

CourseManagement/Areas/Admin/Views/AdminAccounts/ChangePassword.cshtml
@model CourseManagement.Models.Account

@{
    ViewData["Title"] = "Thay đổi mật khẩu tài khoản";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<!-- ======= #main ======= -->
<main id="main" class="main">
    <!-- Page Title -->
    <div class="pagetitle">
        <h1>@ViewData["Title"]</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"> <a asp-area="Admin" asp-controller="Home" asp-action="Index">Trang chủ Admin</a> </li>
                <li class="breadcrumb-item"> <a asp-area="Admin" asp-controller="AdminAccounts" asp-action="Index">Quản lý tài khoản</a> </li>
                <li class="breadcrumb-item active">@ViewData["Title"]</li>
            </ol>
        </nav>
    </div>
    <!-- End Page Title -->
    <!-- Section -->
    <section class="section">
        <div class="row">
            <div class="col-lg-6">

                <div class="card">
                    <div class="card-body">


                        <!-- Card Title -->
                        <div class="card-title">
                        </div>
                        <!-- End Card Title -->

                        <!-- Form -->
                        <form class="row g-3" asp-action="ChangePassword">

                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="form-group col-md-12">
                                <input asp-for="Username" type="text" class="form-control" placeholder="Tài khoản" readonly />
                                <span asp-validation-for="Username" class="text-danger"></span>
                            </div>

                            <div class="form-group col-md-12">
                                <input asp-for="Password" type="password" class="form-control" placeholder="Mật khẩu mới" />
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>

                            <div class="form-group col-md-12">
                                <input asp-for="Fullname" type="text" class="form-control" placeholder="Họ và tên" readonly />
                                <span asp-validation-for="Fullname" class="text-danger"></span>
                            </div>

                            <div class="form-group col-md-12">
                                <input asp-for="Phone" type="number" class="form-control" placeholder="Số điện thoại" readonly />
                                <span asp-validation-for="Phone" class="text-danger"></span>
                            </div>

                            <div class="form-group col-md-6">
                                <select class="form-select" asp-for="IdRole" asp-items="ViewBag.IdRole" required readonly>
                                    <option value="0" readonly selected>Quyền truy cập</option>
                                </select>
                            </div>

                            <div class="form-group col-12">
                                <div class="form-check form-switch">
                                    <input asp-for="Active" class="form-check-input" type="checkbox" id="gridCheck" readonly />
                                    <span asp-validation-for="Active" class="text-danger"></span>
                                    <label class="form-check-label" for="gridCheck">
                                        Kích hoạt
                                    </label>
                                </div>
                            </div>

                            <div class="btn-group">
                                <input type="hidden" asp-for="IdAccount" />
                                <button class="btn btn-outline-info">
                                    <i class="bi bi-gear"></i> Đổi mật khẩu
                                </button>
                                <a type="button" class="btn btn-outline-danger" asp-area="Admin" asp-controller="AdminAccounts" asp-action="Index">
                                    <i class="bi bi-x-circle"></i> Hủy
                                </a>
                            </div>

                        </form>
                        <!-- End Form -->


                    </div>
                </div>

            </div>
        </div>
    </section>
    <!-- End Section -->
</main>
<!-- End #main -->

CourseManagement/Areas/Admin/Views/AdminAccounts/Create.cshtml
@model CourseManagement.Models.Account

@{
    ViewData["Title"] = "Tạo mới tài khoản";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<!-- ======= #main ======= -->
<main id="main" class="main">
    <!-- Page Title -->
    <div class="pagetitle">
        <h1>@ViewData["Title"]</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"> <a asp-area="Admin" asp-controller="Home" asp-action="Index">Trang chủ Admin</a> </li>
                <li class="breadcrumb-item"> <a asp-area="Admin" asp-controller="AdminAccounts" asp-action="Index">Quản lý tài khoản</a> </li>
                <li class="breadcrumb-item active">@ViewData["Title"]</li>
            </ol>
        </nav>
    </div>
    <!-- End Page Title -->
    <!-- Section -->
    <section class="section">
        <div class="row">
            <div class="col-lg-6">

                <div class="card">
                    <div class="card-body">


                        <!-- Card Title -->
                        <div class="card-title">
                        </div>
                        <!-- End Card Title -->
                        <!-- Form -->
                        <form class="row g-3" asp-action="Create">

                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="form-group col-md-12">
                                <input asp-for="Username" type="text" class="form-control" placeholder="Tài khoản" required />
                                <span asp-validation-for="Username" class="text-danger"></span>
                            </div>

                            <div class="form-group col-md-12">
                                <input asp-for="Password" type="password" class="form-control" placeholder="Mật khẩu" required>
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>

                            <div class="form-group col-md-12">
                                <input asp-for="Fullname" type="text" class="form-control" placeholder="Họ và tên" required />
                                <span asp-validation-for="Fullname" class="text-danger"></span>
                            </div>

                            <div class="form-group col-md-12">
                                <input asp-for="Phone" type="number" class="form-control" placeholder="Số điện thoại" required />
                                <span asp-validation-for="Phone" class="text-danger"></span>
                            </div>

                            

                            <div class="form-group col-md-6">
                                <select class="form-select" asp-for="IdRole" asp-items="ViewBag.IdRole" required>
                                    <option value="0" disabled selected>Quyền truy cập</option>
                                </select>
                            </div>

                            <div class="form-group col-sm-6">

                                <div class="form-check form-switch">
                                    <input asp-for="Active" class="form-check-input" type="checkbox" id="gridCheck" />
                                    <span asp-validation-for="Active" class="text-danger"></span>
                                    <label class="form-check-label" for="gridCheck">
                                        Kích hoạt
                                    </label>
                                </div>

                            </div>

                            <div class="btn-group">
                                <button class="btn btn-outline-primary">
                                    <i class="bi bi-person-plus"></i> Tạo mới
                                </button>
                                <a type="button" class="btn btn-outline-danger" asp-area="Admin" asp-controller="AdminAccounts" asp-action="Index">
                                    <i class="bi bi-x-circle"></i> Hủy
                                </a>
                            </div>

                        </form>
                        <!-- End Form -->


                    </div>
                </div>

            </div>
        </div>
    </section>
    <!-- End Section -->
</main>
<!-- End #main -->

CourseManagement/Areas/Admin/Views/AdminAccounts/Edit.cshtml
@model CourseManagement.Models.Account

@{
    ViewData["Title"] = "Chỉnh sửa tài khoản";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<!-- ======= #main ======= -->
<main id="main" class="main">
    <!-- Page Title -->
    <div class="pagetitle">
        <h1>@ViewData["Title"]</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"> <a asp-area="Admin" asp-controller="Home" asp-action="Index">Trang chủ Admin</a> </li>
                <li class="breadcrumb-item"> <a asp-area="Admin" asp-controller="AdminAccounts" asp-action="Index">Quản lý tài khoản</a> </li>
                <li class="breadcrumb-item active">@ViewData["Title"]</li>
            </ol>
        </nav>
    </div>
    <!-- End Page Title -->
    <!-- Section -->
    <section class="section">
        <div class="row">
            <div class="col-lg-6">

                <div class="card">
                    <div class="card-body">


                        <!-- Card Title -->
                        <div class="card-title">
                        </div>
                        <!-- End Card Title -->
                        <!-- Form -->
                        <form class="row g-3" asp-action="Edit">

                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="form-group col-4">
                                <a type="button" class="btn btn-outline-info" asp-action="ChangePassword" asp-area="Admin" asp-controller="AdminAccounts" asp-route-id="@Model.IdAccount">
                                    <i class="bi bi-gear"></i> Đổi mật khẩu
                                </a>
                            </div>

                            <div class="form-group col-md-12">
                                <input asp-for="Username" type="text" class="form-control" placeholder="Tài khoản" required />
                                <span asp-validation-for="Username" class="text-danger"></span>
                            </div>

                            <div class="form-group col-md-12">
                                <input asp-for="Password" type="text" class="form-control text-danger" placeholder="Mật khẩu" readonly />
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>

                            <div class="form-group col-md-12">
                                <input asp-for="Fullname" type="text" class="form-control" placeholder="Họ và tên" required />
                                <span asp-validation-for="Fullname" class="text-danger"></span>
                            </div>

                            <div class="form-group col-md-12">
                                <input asp-for="Phone" type="number" class="form-control" placeholder="Số điện thoại" required />
                                <span asp-validation-for="Phone" class="text-danger"></span>
                            </div>

                            <div class="form-group col-md-6">
                                <select class="form-select" asp-for="IdRole" asp-items="ViewBag.IdRole" required>
                                    <option value="0" disabled selected>Quyền truy cập</option>
                                </select>
                            </div>

                            <div class="form-group col-sm-6">

                                <div class="form-check form-switch">
                                    <input asp-for="Active" class="form-check-input" type="checkbox" id="gridCheck" />
                                    <span asp-validation-for="Active" class="text-danger"></span>
                                    <label class="form-check-label" for="gridCheck">
                                        Kích hoạt
                                    </label>
                                </div>

                            </div>

                            <div class="btn-group">
                                <input type="hidden" asp-for="IdAccount" />
                                <button class="btn btn-outline-warning">
                                    <i class="bi bi-save"></i> Lưu
                                </button>
                                <a type="button" class="btn btn-outline-danger" asp-area="Admin" asp-controller="AdminAccounts" asp-action="Index">
                                    <i class="bi bi-x-circle"></i> Hủy
                                </a>
                            </div>
                        </form>
                        <!-- End Form -->


                    </div>
                </div>

            </div>
        </div>
    </section>
    <!-- End Section -->
</main>
<!-- End #main -->

CourseManagement/Areas/Admin/Views/AdminAccounts/Login.cshtml
@model CourseManagement.Areas.Admin.Models.LoginViewModel
@{
    ViewData["Title"] = "Đăng nhập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<main>
    <div class="container">

        <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
            <div class="container">

                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

                        <div class="card mb-3">

                            <div class="card-body">

                                @if (ViewBag.Error == null)
                                {
                                    <div class="pt-4 pb-2">
                                        <h5 class="card-title text-center pb-0 fs-4">Đăng nhập</h5>
                                        <p class="text-center small">Nhập "tài khoản" và "mật khẩu" để truy cập</p>
                                    </div>
                                }
                                else
                                {
                                    <div class="pt-4 pb-2">
                                        <h5 class="card-title text-center pb-0 fs-4">Đăng nhập thất bại</h5>
                                        <p class="text-danger text-center">@ViewBag.Error</p>
                                    </div>
                                }
                                <form class="row g-3 needs-validation" novalidate asp-action="Login" method="post">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                                    <div class="col-12">

                                            <i class="bi bi-file-person-fill"></i>
                                            <label for="yourUsername" class="form-label text-primary">Username</label>

                                        <div class="input-group has-validation">
                                            <input type="text" name="username" class="form-control text-success" id="yourUsername" asp-for="UserName" placeholder="Tài khoản" required>
                                            <span asp-validation-for="UserName" class="text-danger"></span>
                                            <div class="invalid-feedback">Vui lòng nhập tài khoản</div>
                                        </div>
                                    </div>

                                    <div class="col-12">

                                        <i class="bi bi-keyboard-fill"></i>
                                        <label for="yourPassword" class="form-label text-primary">Password</label>

                                        <div class="input-group has-validation">
                                            <input type="password" name="password" class="form-control text-success" id="yourPassword" asp-for="Password" placeholder="Mật khẩu" required>
                                            <span asp-validation-for="Password" class="text-danger"></span>
                                            <div class="invalid-feedback">Vui lòng nhập mật khẩu</div>
                                        </div>
                                    </div>

                                    <div class="btn-group col-12">
                                        <button class="btn btn-primary w-50" type="submit">
                                            <i class="bi bi-box-arrow-in-right"></i> Đăng nhập
                                        </button>
                                        <a class="btn btn-info w-50" href="/">
                                            <i class="bi bi-building"></i> Quay về  
                                        </a>
                                    </div>

                                </form>

                            </div>
                        </div>

                    </div>
                </div>

            </div>

        </section>

    </div>
</main><!-- End #main -->