CourseManagement/Areas/Admin/Controllers/AdminCoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CourseManagement.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using AspNetCoreHero.ToastNotification.Abstractions;
using PagedList.Core;
using System.IO;
using CourseManagement.Helpper;
using Microsoft.AspNetCore.Hosting;



namespace CourseManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,Editor")]
    public class AdminCoursesController : Controller
    {
        private readonly CourseDatabaseContext _context;
        public INotyfService _notyf;

        public AdminCoursesController(CourseDatabaseContext context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }

        private string GetUniqueFileName(string fileName)
        {
            fileName = Path.GetFileName(fileName);
            return Path.GetFileNameWithoutExtension(fileName)
                      + "_"
                      + Guid.NewGuid().ToString().Substring(0, 4)
                      + Path.GetExtension(fileName);
        }

        public IActionResult Index(int page = 1, int IdCategory = 0)
        {
            var pageNumber = page;
            var pageSize = 10;

            List<Course> lsCourses = new List<Course>();

            if (IdCategory != 0)
            {
                lsCourses = _context.Courses
                .AsNoTracking()
                .Where(x => x.IdCategory == IdCategory)
                .Include(x => x.IdCategoryNavigation)
                .OrderBy(x => x.IdCourse).ToList();
            }
            else
            {
                lsCourses = _context.Courses
                .AsNoTracking()
                .Include(x => x.IdCategoryNavigation)
                .OrderBy(x => x.IdCourse).ToList();
            }

            PagedList<Course> models = new PagedList<Course>(lsCourses.AsQueryable(), pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            ViewBag.PageLength = (int)Math.Ceiling((Double)lsCourses.Count / (Double)pageSize);
            ViewBag.CurrentIdCategory = IdCategory;
            ViewData["IdCategory"] = new SelectList(_context.Categories, "IdCategory", "Name");
            return View(models);
        }

        public IActionResult Create()
        {
            ViewData["IdCategory"] = new SelectList(_context.Categories, "IdCategory", "Name");
            _notyf.Information("Đang thêm mới");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCourse,Name,Description,IdCategory,Image,Price,Active")] Course course, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                 if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string image = Utilities.SEOUrl(course.Name) + extension;
                        course.Image = await Utilities.UploadFile(fThumb, @"Courses", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(course.Image)) course.Image = "default.jpg";
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCategory"] = new SelectList(_context.Categories, "IdCategory", "Name", course.IdCategory);
            _notyf.Success("Tạo mới thành công");
            return View(course);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            _notyf.Warning("Đang chỉnh sửa");
            ViewData["IdCategory"] = new SelectList(_context.Categories, "IdCategory", "Name", course.IdCategory);
            return View(course);
        }

     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCourse,Name,Description,IdCategory,Image,Price,Active")] Course course, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != course.IdCourse)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string image = Utilities.SEOUrl(course.Name) + extension;
                        course.Image = await Utilities.UploadFile(fThumb, @"Courses", image.ToLower());
                    }

                    if (string.IsNullOrEmpty(course.Image)) course.Image = "default.jpg";

                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.IdCourse))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                _notyf.Success("Chỉnh sửa thành công");
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCategory"] = new SelectList(_context.Categories, "IdCategory", "Name", course.IdCategory);
            return View(course);
        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.IdCategoryNavigation)
                .FirstOrDefaultAsync(m => m.IdCourse == id);
            if (course == null)
            {
                return NotFound();
            }
            _notyf.Error("Xác nhận xóa");
            return View(course);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Courses == null)
            {
                return Problem("Entity set 'CourseDatabaseContext.Courses'  is null.");
            }
            var course = await _context.Courses.FindAsync(id);
            if (course != null)
            {
                _context.Courses.Remove(course);
            }
            
            await _context.SaveChangesAsync();
            _notyf.Success("Xóa thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
          return _context.Courses.Any(e => e.IdCourse == id);
        }
    }
}

CourseManagement/Areas/Admin/Controllers/AdminRolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CourseManagement.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using AspNetCoreHero.ToastNotification.Abstractions;
using PagedList.Core;

namespace CourseManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,Editor")]
    public class AdminRolesController : Controller
    {
        private readonly CourseDatabaseContext _context;
        public INotyfService _notyf;

        public AdminRolesController(CourseDatabaseContext context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }

        // GET: Admin/AdminRoles
        public IActionResult Index(int page = 1)
        {
            var pageNumber = page;
            var pageSize = 10;

            List<Role> lsRoles = new List<Role>();

            lsRoles = _context.Roles
            .AsNoTracking()
                .OrderBy(x => x.IdRole).ToList();

            PagedList<Role> models = new PagedList<Role>(lsRoles.AsQueryable(), pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            ViewBag.PageLength = (int)Math.Ceiling((Double)lsRoles.Count / (Double)pageSize);

            return View(models);
        }



        public IActionResult Create()
        {
            _notyf.Information("Đang thêm mới");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdRole,Name,Description")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                _notyf.Success("Tạo mới thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            _notyf.Warning("Đang chỉnh sửa");
            return View(role);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdRole,Name,Description")] Role role)
        {
            if (id != role.IdRole)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.IdRole))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                _notyf.Success("Chỉnh sửa thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.IdRole == id);
            if (role == null)
            {
                return NotFound();
            }
            _notyf.Error("Xác nhận xóa");
            return View(role);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Roles == null)
            {
                return Problem("Entity set 'CourseDatabaseContext.Roles'  is null.");
            }
            var role = await _context.Roles.FindAsync(id);
            if (role != null)
            {
                _context.Roles.Remove(role);
            }
            
            await _context.SaveChangesAsync();
            _notyf.Success("Xóa thành công");
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
          return _context.Roles.Any(e => e.IdRole == id);
        }
    }
}

CourseManagement/Areas/Admin/Views/Shared/AdminError.cshtml
@{
    ViewData["Title"] = "Lỗi Admin Share";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

CourseManagement/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>

    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/Admin/assets/img/favicon.png" rel="icon">
    <link href="~/Admin/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Alegreya:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,600,600i,700,700i|Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/Admin/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Admin/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/Admin/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/Admin/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/Admin/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/Admin/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/Admin/assets/vendor/simple-datatables/style.css" rel="stylesheet">
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />


    <!-- Template Main CSS File -->
    <link href="~/Admin/assets/css/style.css" rel="stylesheet">

    @await RenderSectionAsync("Styles", required: false)
</head>
<body>

    @if (User.Identity.IsAuthenticated)
    {
        <!-- ======= Header ======= -->
        @await Html.PartialAsync("_HeaderPartialView.cshtml")
        <!-- End Header -->
        <!-- ======= Sidebar ======= -->
        @await Html.PartialAsync("_SidebarPartialView.cshtml")
        <!-- End Sidebar-->
    }

    <!-- ======= Body ======= -->
    @RenderBody()
    <!-- End Body -->
    @if (User.Identity.IsAuthenticated)
    {
        <!-- ======= Footer ======= -->
        @await Html.PartialAsync("_FooterPartialView.cshtml")
        <!-- End Footer -->
    }

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


    <!-- Vendor JS Files -->
    <script src="~/Admin/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/Admin/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Admin/assets/vendor/chart.js/chart.min.js"></script>
    <script src="~/Admin/assets/vendor/echarts/echarts.min.js"></script>
    <script src="~/Admin/assets/vendor/quill/quill.min.js"></script>
    <script src="~/Admin/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/Admin/assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/Admin/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/Admin/assets/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>*@

    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CourseManagement/Areas/Admin/Views/Shared/_FooterPartialView.cshtml
@*<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright <strong><span>Admin Courses</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
        Customized for the course management page by <a href="https://fb.com/ngngvng">Ngô Nguyễn Vương</a>
    </div>
</footer>*@

CourseManagement/Areas/Admin/Views/Shared/_HeaderPartialView.cshtml
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a class="logo d-flex align-items-center" asp-area="Admin" asp-controller="AdminDashboard" asp-action="Index">
            <img src="~/Admin/assets/img/logo.png" alt="">
            <span class="d-none d-lg-block">Admin Course</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->


        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <span class="d-none d-md-block dropdown-toggle ps-2">@User.Identity.Name</span>
                    </a><!-- End Profile Iamge Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="/dang-xuat.html">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Đăng xuất</span>
                            </a>
                        </li>

                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->

            </ul>
        </nav>

        <!-- End Icons Navigation -->

   

</header>

CourseManagement/Areas/Admin/Views/Shared/_SidebarPartialView.cshtml
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-heading">@User.Identity.Name</li>

        <li class="nav-item">
            <a class="nav-link collapsed" asp-area="Admin" asp-controller="AdminDashboard" asp-action="Index">
                <i class="bi bi-person-badge"></i>
                <span>Thông tin cá nhân</span>
            </a>
        </li>

        <li class="nav-heading">Courses Management</li>
        @if (User.IsInRole("Admin") || User.IsInRole("Editor"))
        {
            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="Admin" asp-controller="AdminCourses" asp-action="Index">
                    <i class="bi bi-book-half"></i>
                    <span>Quản lý khóa học</span>
                </a>
            </li>
           
            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="Admin" asp-controller="AdminCalendars" asp-action="Index">
                    <i class="bi bi-calendar-week"></i>
                    <span>Quản lý lịch học</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="Admin" asp-controller="AdminContacts" asp-action="Index">
                    <i class="bi bi-clipboard-data"></i>
                    <span>Quản lý đăng ký lịch học</span>
                </a>
            </li>

        }

        @if (User.IsInRole("Admin"))
        {
            <li class="nav-heading">Database</li>

            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="Admin" asp-controller="AdminAccounts" asp-action="Index">
                    <i class="bi bi-person-square"></i>
                    <span>Quản lý tài khoản</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="Admin" asp-controller="AdminCategories" asp-action="Index">
                    <i class="bi bi-stack"></i>
                    <span>Quản lý danh mục</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="Admin" asp-controller="AdminRoles" asp-action="Index">
                    <i class="bi bi-diagram-3"></i>
                    <span>Quản lý quyền truy cập</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" asp-area="Admin" asp-controller="AdminStatuses" asp-action="Index">
                    <i class="bi bi-ui-checks"></i>
                    <span>Quản lý trạng thái đăng ký</span>
                </a>
            </li>

        }
        <!-- End Databases Nav -->


    </ul>

</aside>