CourseManagement/Areas/Admin/Controllers/AdminLearnsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CourseManagement.Models;
using Microsoft.AspNetCore.Authorization;
using PagedList.Core;
using AspNetCoreHero.ToastNotification.Abstractions;
using System.Globalization;

namespace CourseManagement.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]

    public class AdminLearnsController : Controller
    {
        private readonly CourseDatabaseContext _context;
        public INotyfService _notyf;

        public AdminLearnsController(CourseDatabaseContext context, INotyfService notyf)
        {
            _context = context;
            _notyf = notyf;
        }


        public async Task<IActionResult> Index(int IdCalendar = 0, int page = 1)
        {
            var calendar = await _context.Calendars
                  .Include(c => c.IdCourseNavigation)
                  .Include(x => x.IdTeacherNavigation)
                  .SingleOrDefaultAsync(m => m.IdCalendar == IdCalendar);

            if (calendar == null)
            {
                return RedirectToAction("Index", "AdminCalendars");
            }

            if (calendar.IdCourseNavigation.Active == false)
            {
                calendar.Active = false;
                _context.Calendars.Update(calendar);

                await _context.SaveChangesAsync();

                _notyf.Error("Khóa học không còn hoạt động");
                _notyf.Warning("Đã đóng lịch học");

                return RedirectToAction("Index","AdminCalendars");
            }
            else
            {
                var pageNumber = page;
                var pageSize = 10;

                List<Learn> lsLearns = new List<Learn>();

                lsLearns = _context.Learns
                    .AsNoTracking()
                    .Where(x => x.IdCalendar == IdCalendar)
                    .Include(x => x.IdCalendarNavigation)
                    .Include(x => x.IdStudentNavigation)
                    .OrderBy(x => x.IdStudent).ToList();

                PagedList<Learn> models = new PagedList<Learn>(lsLearns.AsQueryable(), pageNumber, pageSize);

                ViewBag.CurrentPage = pageNumber;
                ViewBag.PageLength = (int)Math.Ceiling((Double)lsLearns.Count / (Double)pageSize);
                ViewBag.CurrentIdCalendar = IdCalendar;
                return View(models);
            }
        }

        public async Task<IActionResult> Create(int IdCalendar = 0)
        {

            var calendar = await _context.Calendars
                .Include(c => c.IdCourseNavigation)
                .Include(x => x.IdTeacherNavigation)
                .FirstOrDefaultAsync(m => m.IdCalendar == IdCalendar);

            if (calendar.Slotnow == calendar.Slotmax)
            {
                _notyf.Warning("Lịch học đã hết chỗ");
                return RedirectToAction(nameof(Index), new { IdCalendar });
            }


            ViewData["IdCalendar"] = new SelectList(_context.Calendars.Where(x => x.IdCalendar == IdCalendar), "IdCalendar", "Name");
            ViewData["IdStudent"] = new SelectList(_context.Accounts.Where(x => (x.IdRoleNavigation.Name == "Student" && x.Active)), "IdAccount", "Fullname");
            _notyf.Information("Đang thêm học viên");
            ViewBag.CurrentIdCalendar = IdCalendar;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdStudent,IdCalendar,IdLearn")] Learn learn, int IdCalendar)
        {
            if (ModelState.IsValid)
            {
                var calendar = await _context.Calendars
                .Include(c => c.IdCourseNavigation)
                .Include(x => x.IdTeacherNavigation)
                .FirstOrDefaultAsync(m => m.IdCalendar == learn.IdCalendar);

                var _learn = await _context.Learns
                .Include(c => c.IdCalendarNavigation)
                .Include(x => x.IdStudentNavigation)
                .Where(m => m.IdCalendar == learn.IdCalendar)
                .FirstOrDefaultAsync(m => m.IdStudent == learn.IdStudent);

                if (calendar == null || _learn != null)
                {
                    _notyf.Warning("Học viên đã được thêm");
                    return RedirectToAction(nameof(Index), new { IdCalendar });
                }

                calendar.Slotnow++;
                _context.Update(calendar);

                learn.IdCalendar = IdCalendar;
                _context.Add(learn);

                await _context.SaveChangesAsync();
                _notyf.Success("Tạo mới thành công");
                return RedirectToAction(nameof(Index), new { IdCalendar });
            }

            _notyf.Error("Tạo mới không thành công");
            return RedirectToAction(nameof(Index), new { IdCalendar });
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Learns == null)
            {
                return NotFound();
            }

            var learn = await _context.Learns
                .Include(c => c.IdCalendarNavigation)
                .Include(x => x.IdStudentNavigation)
                .FirstOrDefaultAsync(m => m.IdLearn == id);

            int IdCalendar = learn.IdCalendar;

            if (learn == null)
            {
                _notyf.Error("Đã xảy ra lỗi khi xóa");
                return RedirectToAction(nameof(Index), new { IdCalendar });
            }

            _notyf.Error("Xác nhận xóa học viên");
            return View(learn);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (_context.Learns == null)
            {
                return Problem("Entity set 'CourseDatabaseContext.Learns'  is null.");
            }
            var learn = await _context.Learns.FindAsync(id);

            int IdCalendar = learn.IdCalendar;

            if (learn != null)
            {
                var calendar = await _context.Calendars
                .Include(c => c.IdCourseNavigation)
                .Include(x => x.IdTeacherNavigation)
                .FirstOrDefaultAsync(m => m.IdCalendar == learn.IdCalendar);

                if (calendar == null)
                {
                    _notyf.Error("Đã xảy ra lỗi khi xóa");
                    return RedirectToAction(nameof(Index), new { IdCalendar });
                }

                calendar.Slotnow--;
                _context.Update(calendar);
                _context.Learns.Remove(learn);
            }

            await _context.SaveChangesAsync();
            _notyf.Success("Xóa thành công");
            return RedirectToAction(nameof(Index), new { IdCalendar });
        }

        private bool LearnExists(int id)
        {
            return _context.Learns.Any(e => e.IdLearn == id);
        }
    }
}

CourseManagement/Areas/Admin/Views/AdminLearns/Create.cshtml
@model CourseManagement.Models.Learn

@{
    ViewData["Title"] = "Thêm mới học viên";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<!-- ======= #main ======= -->
<main id="main" class="main">
    <!-- Page Title -->
    <div class="pagetitle">
        <h1>@ViewData["Title"]</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"> <a asp-area="Admin" asp-controller="Home" asp-action="Index">Trang chủ Admin</a> </li>
                <li class="breadcrumb-item"> <a asp-area="Admin" asp-controller="AdminCategories" asp-action="Index">Quản lý danh mục</a> </li>
                <li class="breadcrumb-item active">@ViewData["Title"]</li>
            </ol>
        </nav>
    </div>
    <!-- End Page Title -->
    <!-- Section -->
    <section class="section">
        <div class="row">
            <div class="col-lg-6">

                <div class="card">
                    <div class="card-body">


                        <!-- Card Title -->
                        <div class="card-title">
                        </div>
                        <!-- End Card Title -->

                        <!-- Form -->
                        <form class="row g-3" asp-action="Create">

                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="form-group col-md-12">
                                <label for="formIdStudent">Học viên</label>
                                <select class="form-select" asp-for="IdStudent" asp-items="ViewBag.IdStudent" id="formIdStudent" required>
                                    <option value="0" disabled selected>Chọn học viên</option>
                                </select>
                            </div>

                            <div class="form-group col-md-12">
                                <label for="formIdCalendar">Lịch học</label>
                                <select class="form-select" asp-for="IdCalendar" asp-items="ViewBag.IdCalendar" id="formIdCalendar" required>
                                </select>
                            </div>

                            <div class="btn-group">
                                <button class="btn btn-outline-primary">
                                    <i class="bi bi-person-plus"></i> Tạo mới
                                </button>
                                <a type="button" class="btn btn-outline-danger" href="/Admin/AdminLearns/Index?IdCalendar=@ViewBag.CurrentIdCalendar&Page=1">
                                    <i class="bi bi-x-circle"></i> Hủy
                                </a>
                            </div>

                        </form>
                        <!-- End Form -->


                    </div>
                </div>

            </div>
        </div>
    </section>
    <!-- End Section -->
</main>
<!-- End #main -->

CourseManagement/Areas/Admin/Views/AdminLearns/Delete.cshtml
@model CourseManagement.Models.Learn

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Learn</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCalendarNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCalendarNavigation.IdCalendar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdStudentNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdStudentNavigation.IdAccount)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdLearn" redirect="/Admin/AdminLearns/Create?IdCalendar=7" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CourseManagement/Areas/Admin/Views/AdminLearns/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<CourseManagement.Models.Learn>

@{
    ViewData["Title"] = "Quản lý lớp học #" + @ViewBag.CurrentIdCalendar;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    int PageCurrent = ViewBag.CurrentPage;
    int PageLength = ViewBag.PageLength;
    int PageBack = PageCurrent - 1;
    int PageNext = PageCurrent + 1;
    int PageNextPlus = PageNext + 1;
    int PageNextMinus = PageBack - 1;
}

<!-- ======= #main ======= -->
<main id="main" class="main">
    <!-- Page Title -->
    <div class="pagetitle">
        <h1>@ViewData["Title"]</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"> <a asp-area="Admin" asp-controller="Home" asp-action="Index">Trang chủ Admin</a> </li>
                <li class="breadcrumb-item"> <a asp-area="Admin" asp-controller="AdminCalendars" asp-action="Index">Quản lý lịch học</a> </li>
                <li class="breadcrumb-item active">
                    @ViewData["Title"]
                </li>
            </ol>
        </nav>
    </div>
    <!-- End Page Title -->
    <!-- Section -->
    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">


                        <!-- Card Title -->
                        <div class="card-title">
                            <a type="button" class="btn btn-outline-primary" href="/Admin/AdminLearns/Create?IdCalendar=@ViewBag.CurrentIdCalendar">
                                <i class="bi bi-file-plus-fill"></i> Thêm học viên
                            </a>

                            <a type="button" class="btn btn-outline-primary" asp-action="Index" asp-area="Admin" asp-controller="AdminCalendars">
                                <i class="bi bi-reply-fill"></i> Trở về
                            </a>
                        </div>
                        <!-- End Card Title -->
                        <!-- Table -->
                        <table class="table">
                            <thead>
                                <tr class="table-info text-center">
                                    <th scope="col">ID</th>
                                    <th scope="col">Họ và tên học viên</th>
                                    <th scope="col">Thêm</th>
                                </tr>
                            </thead>
                            <tbody>

                                @Html.Hidden("item-to-delete", "", new {@id = "item-to-delete"})

                                @foreach (var item in Model)
                                {
                                    <tr class="text-center">

                                        <th scope="row">
                                                @item.IdStudentNavigation.IdAccount
                                        </th>

                                        <th scope="row">
                                                @item.IdStudentNavigation.Fullname
                                        </th>

                                        <td>
                                            <div class="btn-group">

                                                <a type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#_Delete_@item.IdLearn" asp-route-id="@item.IdLearn">
                                                    <i class="bi bi-eraser-fill"></i> Xóa
                                                </a>

                                            </div>

                                            <!-- Modal Delete -->
                                            <div class="modal fade" id="_Delete_@item.IdLearn" tabindex="-1">
                                                <div class="modal-dialog">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title">Bạn chắc chắn muốn xóa #@item.IdLearn</h5>
                                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <!-- Table -->
                                                            <table class="table">
                                                                <tbody>
                                                                    <tr class="text-center">
                                                                        <th scope="col">Học viên: </th>
                                                                        <th scope="row">@item.IdStudentNavigation.Fullname</th>
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                            <!-- End Table -->
                                                        </div>
                                                        <div class="modal-footer">

                                                            <form asp-action="Delete" asp-area="Admin" asp-controller="AdminLearns" asp-route-id="@item.IdLearn">
                                                                <button class="btn btn-outline-danger">
                                                                    <i class="bi bi-eraser-fill"></i> Xóa
                                                                </button>

                                                                <a type="button" class="btn btn-outline-primary" asp-area="Admin" data-bs-dismiss="modal">
                                                                    <i class="bi bi-reply-fill"></i> Trở về
                                                                </a>
                                                            </form>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- End Modal Delete-->

                                        </td>



                                    </tr>
                                }
                            </tbody>
                        </table>
                        <!-- End Table -->

                    </div>

                </div>
            </div>
        </div>
    </section>
    <!-- End Section -->
    <!-- Pagination -->
    <nav aria-label="Page navigation">
        <ul class="pagination">
            @if (PageCurrent > 1)
            {
                <li class="page-item">
                    <a class="page-link" href="?Page=1" aria-label="Previous">
                        <span class="fa fa-chevron-left"></span>
                    </a>
                </li>
                if (PageNextMinus >= 1)
                {
                    <li class="page-item"><a class="page-link" href="?Page=@PageNextMinus">@PageNextMinus</a></li>
                }
                <li class="page-item"><a class="page-link" href="?Page=@PageBack">@PageBack</a></li>
            }
            else
            {
                <li class="page-item disabled">
                    <a class="page-link" href="?Page=1" aria-label="Previous">
                        <span class="fa fa-chevron-left"></span>
                    </a>
                </li>
            }

            <li class="page-item active"><a class="page-link" href="?Page=@PageCurrent">@PageCurrent</a></li>

            @if (PageCurrent < PageLength)
            {
                <li class="page-item"><a class="page-link" href="?Page=@PageNext">@PageNext</a></li>
                if (PageNextPlus <= PageLength)
                {
                    <li class="page-item"><a class="page-link" href="?Page=@PageNextPlus">@PageNextPlus</a></li>
                }
                <li class="page-item">
                    <a class="page-link" href="?Page=@PageLength" aria-label="Next">
                        <span class="fa fa-chevron-right"></span>
                    </a>
                </li>
            }
            else
            {
                <li class="page-item disabled">
                    <a class="page-link" href="?Page=1" aria-label="Next">
                        <span class="fa fa-chevron-right"></span>
                    </a>
                </li>
            }

        </ul>
    </nav>
    <!-- End Pagination -->

</main>
<!-- End #main -->